### ISSUE TITLE
Client Secret in source code

### ISSUE THREAD

**Issue by majulahsingapuri** [timothytancy/edm-alarm#1]
As much as id love to raise the roof, I also love writing code that is secure. The best way to overcome this is to use an ENV file and commit a template to source control and not the actual one with the live credentials. You will have to purge the commit history and reset it back to the point before you commited the keys and force push the changes up. 

Cheers!

**Comment by timothytancy** [comment]
Thanks for the help Graph! Learning new stuff everyday, this was very helpful :D
